Django/DjangoPractise/website1/music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [ 
    path('', views.index,name='index'),
    path('<int:album_id>/', views.detail,name='detail'),
    path('<int:album_id>/favorite', views.favorite,name='favorite'),
]

Django/DjangoPractise/website1/website/urls.py
from django.contrib import admin
from django.urls import path,include

app_name = 'music'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls')),
    path('music/', include('music.urls')),
]

Django/DjangoPractise/website1/music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genere = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    
    def __str__(self):
        return self.artist+' - '+self.album_title
    
class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    
    def __str__(self):
        return self.song_title

Django/DjangoPractise/website1/music/views.py
from django.shortcuts import render,get_object_or_404
from .models import Album,Song

def index(request):
    all_albums = Album.objects.all()
    return render(request,'music/index.html',{'all_albums':all_albums,})
    
def detail(request,album_id):
    album=get_object_or_404(Album,id=album_id)
    return render(request,'music/details.html',{'album':album})
    
def favorite(request,album_id):
    album=get_object_or_404(Album,id=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST.get('song'))
    except Exception as ex:
        return render(request,'music/favorite.html',{'album':album,'error_message':'Please select a valid '})
    else:    
        selected_song.is_favorite = True
        selected_song.save()
        return render(request,'music/favorite.html',{'album':album})    

Django/DjangoPractise/website1/music/templates/music/details.html
<!DOCTYPE html5>
<html>
<head>
<title> Music Albums for Sales</title>
</head>
<body style="background-color:pink">
<img src="{{ album.album_logo }}" alt='Oops image not found at -"{{album.album_logo}}"' width =400px height=400px >
<h1 style="text-decoration:underline;color:grey"> "{{ album }}" -- album details:</h1>
<table border=1 bordercolor="grey">
<tr>
<th>Artist</th>
<th>Album Title</th>
<th>Genere</th>
<th>Album Location</th>
</tr>
<tr> 
<td>{{ album.artist }}</td>
<td>{{ album.album_title }}</td>
<td>{{ album.genere }}</td>
<td>{{ album.album_logo }}</td>
</tr>

</table>
<br><br>
{% if album.song_set.all %}
<h1 style="text-decoration:underline;color:grey"> Album List  </h1>
<table border=1 bordercolor="grey">
<tr>
<th>Song Title</th>
<th>File Type</th>
</tr>
{% for song in album.song_set.all %}
<tr> 
<td>{{ song.song_title }}</td>
<td>{{ song.file_type }}</td>
</tr>
{% endfor%}
{% else %} 
<h1 style="color:grey"> No Songs found under this album</h1>
{% endif %}
</table>




</body>
</html>

Django/DjangoPractise/website1/music/templates/music/favorite.html
<!DOCTYPE html5>
<html>
<head>
<title> Music Albums for Sales</title>
</head>
<body style="background-color:pink">
<img src="{{ album.album_logo }}" width=400 height=400/>
<h1 style="text-decoration:underline;color:grey"> "{{ album.artist }}" -- album details:</h1>
<form action="{% url 'music:favorite' album.id %}" method="post">
{% csrf_token %}
{% for song in album.song_set.all %}
<input type="radio" id="song{{ forloop.counter }}" name="song" value= "{{ song.id }}" />
<label for="song{{ forloop.counter }}" >
{{ song.song_title }}
{% if song.is_favorite %}
<img src="http://i.imgur.com/b9b13Rd.png"/>
{% endif %}
</label>
<br>
{% endfor %}
<input type='submit' name='favorite' value="favorite">
</form>
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

</body>
</html>

Django/DjangoPractise/website1/music/templates/music/index.html
<!DOCTYPE html5>
<html>
<head>
<title> Music Albums for Sales</title>
</head>
<body>
<h1 style="text-decoration:underline"> Welcome to My Music Albums </h1>
{% if  all_albums %}
<ul> {% for album in all_albums %}
<li> <!--<a href="/music/{{ album.id }}/"> old style usage of hard code url-->
   <!--<a href= "{% url 'music:detail' album.id %}"> {{ album.album_title }}</a></li> -->
   <a href= "{% url 'music:favorite' album.id %}"> {{ album.album_title }}</a></li>
	{% endfor %}
</ul>
{% else %}
<h1> Oops! Please Bare with us we don't have Albums to upload!!! We will upload soon... </h1>
{% endif %}
</body>
</html>